# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Cloud Run

on:
    push:
        branches: ["deploy/cloud-run"]
    workflow_dispatch:

jobs:
    build-app:
        runs-on: ubuntu-latest
        environment: Prod/Cloud Run Demo
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY}}
                  envkey_NEXT_PUBLIC_FIREBASE_CLIENT_APPID: ${{vars.FIREBASE_CLIENT_APPID}}
                  envkey_NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGINGSENDERID: ${{vars.FIREBASE_CLIENT_MESSAGINGSENDERID}}
                  envkey_NEXT_PUBLIC_FIREBASE_CLIENT_STORAGEBUCKET: ${{vars.FIREBASE_CLIENT_STORAGEBUCKET}}
                  envkey_NEXT_PUBLIC_FIREBASE_CLIENT_PROJECTID: ${{vars.FIREBASE_CLIENT_PROJECTID}}
                  envkey_NEXT_PUBLIC_FIREBASE_CLIENT_AUTHDOMAIN: ${{vars.FIREBASE_CLIENT_AUTHDOMAIN}}
                  envkey_NEXT_PUBLIC_FIREBASE_CLIENT_APIKEY: ${{vars.FIREBASE_CLIENT_APIKEY}}
                  envkey_NEXT_PUBLIC_EMULATOR_FIRESTORE_PORT: ${{vars.EMULATOR_FIRESTORE_PORT}}
                  envkey_NEXT_PUBLIC_EMULATOR_AUTH_PORT: ${{vars.EMULATOR_AUTH_PORT}}
                  envkey_NEXT_PUBLIC_EMULATOR_STORAGE_PORT: ${{vars.EMULATOR_STORAGE_PORT}}
                  fail_on_empty: false

            - name: Check envfile
              run: cat .env

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: |
                  npm ci
                  npm run build --if-present
            - name: Upload app
              uses: actions/upload-artifact@v4.1.0
              with:
                  # Artifact name
                  name: app
                  # A file, directory or wildcard pattern that describes what to upload
                  path: ./.next

    deploy-cloud-run:
        runs-on: ubuntu-latest
        environment: Prod/Cloud Run Demo
        needs: build-app
        steps:
            - name: Download app
              uses: actions/download-artifact@v3
              with:
                  # Artifact name
                  name: app
                  # Target path to download the artifact to
                  path: ./.next
